Fixed compile issue on jdk6: Caused by: idobata4j-core/src/main/java/com/uphyca/idobata/transform/ConversionException.java:42: cannot find symbol :idobata4j-core:compileJavabol  : constructor Exception(java.lang.String,java.lang.Throwable,boolean,boolean)